-- MySQL Script generated by MySQL Workbench
-- Tue Nov 10 22:17:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Acme Pharmaceuticals
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Acme Pharmaceuticals
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Acme Pharmaceuticals` DEFAULT CHARACTER SET utf8 ;
USE `Acme Pharmaceuticals` ;

-- -----------------------------------------------------
-- Table `Acme Pharmaceuticals`.`Studies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Acme Pharmaceuticals`.`Studies` (
  `StudyID` INT NOT NULL,
  `Studiescol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StudyID`),
  UNIQUE INDEX `StudyID_UNIQUE` (`StudyID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Acme Pharmaceuticals`.`RandomCodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Acme Pharmaceuticals`.`RandomCodes` (
  `RandomCodeID` INT NOT NULL,
  `RandomCode` INT(4) NOT NULL,
  `StudyID` INT NOT NULL,
  `Treatment` VARCHAR(45) NOT NULL DEFAULT 'A(Active)/P(Placebo)',
  `Available` VARCHAR(1) NULL,
  PRIMARY KEY (`RandomCodeID`),
  INDEX `StudyID_idx` (`StudyID` ASC) VISIBLE,
  CONSTRAINT `StudyID`
    FOREIGN KEY (`StudyID`)
    REFERENCES `Acme Pharmaceuticals`.`Studies` (`StudyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Acme Pharmaceuticals`.`Patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Acme Pharmaceuticals`.`Patients` (
  `PatientID` INT NOT NULL,
  `PatientNumber` INT(11) NOT NULL,
  `SiteID` INT NOT NULL,
  `DOB` DATE NOT NULL,
  `GenderID` INT NOT NULL,
  `Weight` INT(3) NOT NULL,
  `RandomCodeID` INT NULL,
  PRIMARY KEY (`PatientID`),
  UNIQUE INDEX `PatientID_UNIQUE` (`PatientID` ASC) VISIBLE,
  INDEX `SiteID_idx` (`SiteID` ASC) VISIBLE,
  INDEX `GenderID_idx` (`GenderID` ASC) VISIBLE,
  INDEX `RandomCodeID_idx` (`RandomCodeID` ASC) VISIBLE,
  CONSTRAINT `SiteID`
    FOREIGN KEY (`SiteID`)
    REFERENCES `Acme Pharmaceuticals`.`Sites` (`SiteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `RandomCodeID`
    FOREIGN KEY (`RandomCodeID`)
    REFERENCES `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `GenderID`
    FOREIGN KEY (`GenderID`)
    REFERENCES `Acme Pharmaceuticals`.`Genders` (`GenderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Acme Pharmaceuticals`.`WithdrawReasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Acme Pharmaceuticals`.`WithdrawReasons` (
  `WithdrawReasonID` INT NOT NULL,
  `WithdrawDesc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`WithdrawReasonID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Acme Pharmaceuticals`.`Studies`
-- -----------------------------------------------------
START TRANSACTION;
USE `Acme Pharmaceuticals`;
INSERT INTO `Acme Pharmaceuticals`.`Studies` (`StudyID`, `Studiescol`) VALUES (1, 'Study 12345');
INSERT INTO `Acme Pharmaceuticals`.`Studies` (`StudyID`, `Studiescol`) VALUES (2, 'Study 54321');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Acme Pharmaceuticals`.`RandomCodes`
-- -----------------------------------------------------
START TRANSACTION;
USE `Acme Pharmaceuticals`;
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (1, 1000, 1, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (2, 1001, 1, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (3, 1002, 1, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (4, 1003, 1, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (5, 1004, 1, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (6, 1005, 1, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (7, 1006, 1, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (8, 1007, 1, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (9, 1008, 1, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (10, 1009, 1, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (11, 1010, 1, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (12, 1011, 1, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (13, 1012, 1, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (14, 1013, 1, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (15, 1014, 1, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (16, 1015, 1, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (17, 1016, 1, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (18, 1017, 1, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (19, 1018, 1, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (20, 1019, 1, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (21, 5000, 2, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (22, 5001, 2, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (23, 5002, 2, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (24, 5003, 2, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (25, 5004, 2, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (26, 5005, 2, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (27, 5006, 2, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (28, 5007, 2, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (29, 5008, 2, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (30, 5009, 2, 'A', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (31, 5010, 2, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (32, 5011, 2, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (33, 5012, 2, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (34, 5013, 2, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (35, 5014, 2, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (36, 5015, 2, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (37, 5016, 2, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (38, 5017, 2, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (39, 5018, 2, 'P', 'T');
INSERT INTO `Acme Pharmaceuticals`.`RandomCodes` (`RandomCodeID`, `RandomCode`, `StudyID`, `Treatment`, `Available`) VALUES (40, 5019, 2, 'P', 'T');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Acme Pharmaceuticals`.`Patients`
-- -----------------------------------------------------
START TRANSACTION;
USE `Acme Pharmaceuticals`;
INSERT INTO `Acme Pharmaceuticals`.`Patients` (`PatientID`, `PatientNumber`, `SiteID`, `DOB`, `GenderID`, `Weight`, `RandomCodeID`) VALUES (1, 101251, 1, '1994-04-03', 1, 56, 1);
INSERT INTO `Acme Pharmaceuticals`.`Patients` (`PatientID`, `PatientNumber`, `SiteID`, `DOB`, `GenderID`, `Weight`, `RandomCodeID`) VALUES (2, 101252, 1, '1994-04-20', 1, 56, 2);
INSERT INTO `Acme Pharmaceuticals`.`Patients` (`PatientID`, `PatientNumber`, `SiteID`, `DOB`, `GenderID`, `Weight`, `RandomCodeID`) VALUES (3, 101253, 1, '1994-10-22', 1, 45, 3);
INSERT INTO `Acme Pharmaceuticals`.`Patients` (`PatientID`, `PatientNumber`, `SiteID`, `DOB`, `GenderID`, `Weight`, `RandomCodeID`) VALUES (4, 111255, 2, '1994-11-20', 2, 47, 4);
INSERT INTO `Acme Pharmaceuticals`.`Patients` (`PatientID`, `PatientNumber`, `SiteID`, `DOB`, `GenderID`, `Weight`, `RandomCodeID`) VALUES (5, 111256, 2, '1994-10-20', 2, 46, 5);
INSERT INTO `Acme Pharmaceuticals`.`Patients` (`PatientID`, `PatientNumber`, `SiteID`, `DOB`, `GenderID`, `Weight`, `RandomCodeID`) VALUES (6, 111257, 2, '1993-10-20', 2, 75, 6);
INSERT INTO `Acme Pharmaceuticals`.`Patients` (`PatientID`, `PatientNumber`, `SiteID`, `DOB`, `GenderID`, `Weight`, `RandomCodeID`) VALUES (7, 121224, 3, '1992-10-20', 1, 43, 7);
INSERT INTO `Acme Pharmaceuticals`.`Patients` (`PatientID`, `PatientNumber`, `SiteID`, `DOB`, `GenderID`, `Weight`, `RandomCodeID`) VALUES (8, 121226, 3, '1991-10-20', 1, 32, 8);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Acme Pharmaceuticals`.`WithdrawReasons`
-- -----------------------------------------------------
START TRANSACTION;
USE `Acme Pharmaceuticals`;
INSERT INTO `Acme Pharmaceuticals`.`WithdrawReasons` (`WithdrawReasonID`, `WithdrawDesc`) VALUES (1, 'Patient withdrew consent');
INSERT INTO `Acme Pharmaceuticals`.`WithdrawReasons` (`WithdrawReasonID`, `WithdrawDesc`) VALUES (2, 'Adverse event');
INSERT INTO `Acme Pharmaceuticals`.`WithdrawReasons` (`WithdrawReasonID`, `WithdrawDesc`) VALUES (3, 'Health issue-related to study');
INSERT INTO `Acme Pharmaceuticals`.`WithdrawReasons` (`WithdrawReasonID`, `WithdrawDesc`) VALUES (4, 'Health issue-unrelated to study');
INSERT INTO `Acme Pharmaceuticals`.`WithdrawReasons` (`WithdrawReasonID`, `WithdrawDesc`) VALUES (5, 'Personal reason');
INSERT INTO `Acme Pharmaceuticals`.`WithdrawReasons` (`WithdrawReasonID`, `WithdrawDesc`) VALUES (6, 'Completed the study');

COMMIT;

