-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 15:33:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ecommerce` ;

-- -----------------------------------------------------
-- Schema Ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ecommerce` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Ecommerce` ;

-- -----------------------------------------------------
-- Table `Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Customers` (
  `c_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `contact_no` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `Products_idProducts` INT NOT NULL,
  PRIMARY KEY (`c_id`, `Products_idProducts`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Department` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Department` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `deartmentDescription` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Products` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Products` (
  `idProducts` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`idProducts`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Products_has_Sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Products_has_Sales` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Products_has_Sales` (
  `Products_idProducts` INT NOT NULL,
  `Sales_idSales` INT NOT NULL,
  PRIMARY KEY (`Products_idProducts`, `Sales_idSales`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Sales` (
  `idSales` INT NOT NULL,
  `sales_description` VARCHAR(45) NOT NULL,
  `customer_feedback` VARCHAR(45) NULL,
  `Department_id` INT NOT NULL,
  PRIMARY KEY (`idSales`, `Department_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `employee` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `contact` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `designation` VARCHAR(45) NOT NULL,
  `Department_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Department_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
