-- MySQL Script generated by MySQL Workbench
-- Thu Jul 22 14:43:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema workbook
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `workbook` ;

-- -----------------------------------------------------
-- Schema workbook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workbook` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `workbook` ;

-- -----------------------------------------------------
-- Table `EmployeeDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EmployeeDetail` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `EmployeeDetail` (
  `e_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `date_of_birth` VARCHAR(45) NOT NULL,
  `month_of_birth` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `citi` VARCHAR(45) NULL,
  `house_number` VARCHAR(45) NULL,
  `data_source_record_id` INT NOT NULL,
  PRIMARY KEY (`e_id`, `data_source_record_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Transaction_Details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction_Details` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Transaction_Details` (
  `Record_id` INT NOT NULL,
  `TransactionID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Record_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `data_source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `data_source` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `data_source` (
  `record_id` INT NOT NULL,
  `datasource_name` VARCHAR(45) NULL,
  PRIMARY KEY (`record_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `Transaction_Details`
-- -----------------------------------------------------
START TRANSACTION;
USE `workbook`;
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (1, '7fd07bf7-4df1-42a6-a58e-3403514441e1');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (2, 'd237eccd-ca52-4b9d-b0c3-cb05f54ae76c');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (3, 'b01dceaa-93fd-4635-bb8c-24f24e73e139');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (4, '990c87a9-2bd4-4f3a-a469-0040346807bd');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (5, '096620fa-e403-4366-938e-d4e1305321b5');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (6, 'be3b9757-a35a-4aea-86e4-420cdcc0d143');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (7, 'ecbbfdf8-376a-453a-8586-069bd27f4406');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (8, '67e8b63a-8402-44e6-bade-78ad4a7dc885');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (9, '21c00a96-b412-45a7-b7e1-904b2fb37f8a');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (10, '58b51640-2be1-4671-bda2-fe4095c98ec7');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (11, '8cf43c70-56e9-4333-8a7f-7916221765cf');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (12, '9f3068fd-6d1f-4ffa-b006-fdf8ec29e2e3');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (13, '02cb94cb-2dc3-46e4-ba57-fa9f9b6764af');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (14, 'b7c8443f-5dfe-4ef4-bc31-3010a0a9e2f0');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (15, '0ab48fac-e8af-40a8-8390-8977cf2a654b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (16, 'e19cfc1d-cdf8-441c-b798-d42fc50b7ac1');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (17, 'a943908a-67f6-4a89-83c0-f8037b38d2fc');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (18, '75360b01-f934-4a48-bfea-ecce6fd3774f');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (19, 'ab9218c7-c546-42e3-bb76-63bda145c5e6');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (20, '918dc168-b5f2-4ef8-bff0-6fca425adbf8');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (21, 'e9296d1a-4067-4221-99e8-04d1db4614db');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (22, 'a4ed46f9-7316-48ea-80f8-f237105ebe68');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (23, '4c529cdc-a900-4acc-88fb-4ce45585f2a9');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (24, '7888047e-7d35-4f60-879f-c59ecf207839');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (25, '53ff2bd2-1bde-4b92-8bc6-ebfd2b9a9a1e');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (26, '530e82c9-7e30-47a5-9098-3eff4a3537c5');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (27, '29fcf635-54f1-476a-b0dd-9175e4ebca6b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (28, '587274ec-58a6-4b97-9f30-9647f155c0a7');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (29, '2bcd2334-bfab-4465-8f67-96441143cdfd');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (30, '15646ec7-8698-4863-bcf8-c03a07599aec');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (31, '7eeca9e5-7359-4311-b479-458f4ec6ce49');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (32, 'ccf157d5-2090-448a-a2da-cf29387a8f43');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (33, 'd2a1942e-233b-4d10-919b-394f165bb911');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (34, 'a8db0b7f-a1c2-4fe6-83f7-fcd0d2d14af9');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (35, '84aadefa-afdf-47aa-ab24-3fad393f795d');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (36, 'aa71e73f-833a-4c96-941f-d39a9ccc0a73');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (37, '1c24797d-0668-425b-b740-bb71d2b10413');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (38, '408f85a0-0931-4f43-9b0a-a71de5b090cb');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (39, 'be38c1c1-e0d1-4235-addd-ce4628d2a06e');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (40, '9b4bb166-1431-4faa-906c-3dbb8ff16ee5');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (41, '451c297e-f688-4cd9-988c-dff7e0ab4865');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (42, 'a41a3443-0977-4bb4-a7f6-27ed69644e19');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (43, '1c7f23d5-14b2-487b-8521-5bfa9dfd0078');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (44, '133361c4-89ee-4630-8fd0-c9a05d96af2c');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (45, '2ce9bc08-7fe4-4e7f-8fc2-6186eaca40df');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (46, '9d45332c-9284-436f-a018-03979b6be20d');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (47, 'f496468d-6f95-4819-9908-afcd0be75a76');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (48, 'b663ecd4-d325-49d2-aa5b-199011d43871');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (49, 'f3655c02-dd6c-445f-a42c-986f284fa269');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (50, 'ca06d877-694b-4a8a-b764-aade74d21b07');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (51, '7a23fb80-cc1c-4cb0-b1e3-91824c8453d4');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (52, '9dbdbedc-ff0d-49a3-bf94-1fb9915752fd');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (53, '1617120c-d665-4602-a8ed-f2f85822e7fc');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (54, '34b3149c-3408-484d-9100-4924cbe33d7f');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (55, '33825bb8-1e66-42a9-a066-6a1054fea253');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (56, '874db555-ae7a-4c9f-85bd-f77bc24e97da');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (57, '8d3a877e-6ede-435e-837f-f14125b81642');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (58, '71b55b47-124f-4279-8f51-2ed76e58943a');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (59, '95456437-c89f-46c2-923e-b6dbd380b18f');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (60, '9869c662-d7f9-4e31-9f28-964918444cf5');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (61, 'ada46ddf-4e4a-4c59-b3ad-278766dfa6c8');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (62, 'c044c4c9-e696-4671-ba63-cf85a93c3ce2');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (63, '5c0c46f9-07d4-4ba0-8f92-4ebfe1ea0036');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (64, 'ece93bf4-5422-49a5-afdd-2822fe2ea5a4');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (65, '8844141d-c950-4e7b-a7d9-a4f0847985f6');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (66, '8e14a717-04fc-4bac-97a6-1e77671488f2');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (67, '1915f880-64c4-4a75-94d5-5eeee7bc8cb6');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (68, '665827aa-77dc-4172-bde2-792406b623b4');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (69, 'b7815587-a3d9-4025-8daa-8eb68496a78b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (70, '7fe91597-e02f-4846-9499-a766756ddbec');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (71, 'ba24921a-c4e2-4d51-a6ad-8fa46c299cca');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (72, 'aa859b81-aa5b-4840-ab7e-0c570c98be53');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (73, '595a1f37-18f4-4470-b812-4e81af167c4c');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (74, '815a1bb7-854e-4187-bffd-d4dae259f5dd');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (75, 'd4be0350-5ffa-4874-a397-50e042ea714c');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (76, '1165b3be-8d1d-4a7c-bc0b-23c99156c5a0');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (77, '9e6d30f8-9da3-449b-87c1-acb6da0b21ff');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (78, '93a741a8-b241-4f8d-8910-4021f52b5ead');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (79, 'fd9e2659-ec41-4bc5-836a-bde490063041');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (80, '37d5fd47-93c3-48e6-9c8b-1ff61c0f583b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (81, '567aa975-fa72-479b-9cef-4ccbb7604b6c');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (82, '232dfe9b-03ae-4f4f-a8f0-8d2b99a12170');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (83, 'c39cfc46-ba2c-489f-a519-8c29afc1df45');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (84, '94ffa854-7eee-4643-b592-35dbc915995c');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (85, '7520aba7-4080-4ee8-ada4-2a8a9412b000');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (86, '369dde98-c37d-4608-ac07-9a5924f6a74f');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (87, '74345cba-0a68-4e93-ab80-d43f17857f5b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (88, '875fced6-a598-4133-b356-521572a1db6c');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (89, 'd535ed69-487a-4550-b29c-331a168e5c02');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (90, 'f54010e2-c93c-455a-ba5f-f1c590cc9bd7');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (91, '432dd58d-038e-4da0-878d-0971cd1297fe');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (92, '64335a35-921c-4a4f-943d-ccd9e6e8892c');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (93, 'eaae1a96-026d-4f31-b63f-52334acf11e1');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (94, 'e1058dd6-59df-46d7-8b61-eca71791869f');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (95, '4299434c-a31b-4986-83c0-9103d0b20158');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (96, 'c32ae701-8d83-48cf-a17f-e87fa173c9ac');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (97, 'd1c2d2fd-9d4c-4c48-ace3-f7a35262b1ad');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (98, 'e24b19b0-f8f2-4e27-86ee-e958b4d65518');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (99, '9960052f-529b-4f7f-8da1-d0ab2955ee5c');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (100, 'e8eeb1ba-6900-4e86-90f0-48af1d48675e');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (101, '356ccbbc-c452-4c75-9797-ab457a93269a');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (102, '85431690-1486-4224-84e4-30df766103c6');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (103, 'dd16a3da-3288-4d82-b6a0-1d3170b1df8d');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (104, 'ef33d9c9-f074-46c5-9c55-e17e3943191b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (105, '88284411-8e0c-4646-951d-f57baed751d7');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (106, '3a3f8959-57ac-41f1-9284-35d22c92d967');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (107, '7c8d4393-72f7-4f65-b34b-1a8d489789d5');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (108, 'ad4c2dc0-dc33-4669-951e-0aebb0b3722b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (109, 'b9ef2a20-bda4-4eee-986e-b2d6ecc3e311');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (110, '59b5b116-4cb0-470d-9cef-3248e73674a5');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (111, 'ede46556-7451-4e37-a895-3027da8ef73a');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (112, '846fe8be-09cb-48cf-8674-2f4c40af511c');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (113, '7f85d0d1-32fa-4281-a242-01d31091f7ca');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (114, '78ffae3d-c54c-4d61-b21b-6487945a4fe1');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (115, '75ba9b36-a3b6-478d-8f26-c80e2d647f4b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (116, '46bf7a56-bb65-4768-a9ea-d5e6803aa3b4');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (117, '14269ef1-6c0e-459a-8165-325a733b8f05');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (118, '1089107b-2a60-428b-943d-12abd2bc4652');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (119, '09b76fe0-818d-4602-8dcf-1e159e9940fd');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (120, 'ce0c16e6-5ca9-44a8-a6b4-9567a2b34e5e');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (121, '4f02c46d-52b3-4ebe-91bd-1e7009eaa482');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (122, 'd81b9054-21c0-4570-a3d9-5c716735a999');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (123, 'fd927bf5-49a3-407d-a5d4-a7d1df790760');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (124, '7435c808-48b7-4d79-8a17-6c211110a024');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (125, 'e7348c91-f8d9-472a-9bbd-cb0b920e75e4');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (126, 'dae7a4d9-fb77-4592-b870-a2fb47379e0b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (127, '32e3be43-bd3a-45de-a299-8d4d4dfa28d0');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (128, 'bf5f99be-22fd-4fe4-a1ec-e4653258fc58');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (129, '84726091-a5d5-433e-b44f-d519e7d3ff0d');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (130, '1bbab1b0-0068-4ee4-8ee9-cfde11af4ae2');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (131, 'c67d8eec-a10f-4fe8-b1f7-2a0b66cefe76');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (132, '934e6f51-b414-431e-a9c6-366b96e00f1f');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (133, '93326b61-51e5-45c4-98be-ee1129ee393b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (134, '46af2e6d-f5e1-40b3-ae46-35b66cbc48c1');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (135, '490992c9-c5e9-44b3-8f9d-455d21aced02');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (136, '58704f4d-54ff-4e56-bab2-c9d716a6c38b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (137, '9f2f96ad-cb4f-4183-bc06-216ac43ac393');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (138, '960009c6-fc46-4a08-adc5-9d32dcbd8c58');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (139, '5d458013-1a87-4335-a757-69afe48fbb35');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (140, 'f8d8691b-f068-40d2-9c6c-a71cb32a8477');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (141, '8b730c40-4269-4edf-9e13-f65b2773d26d');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (142, 'c734b3ca-5e20-43ba-8d81-97f7b5f6b329');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (143, '6b1f998a-def1-4c04-a166-ef6c04932d44');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (144, 'e3384efe-2b21-4aa7-9bd8-9fcb26531e1d');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (145, '621765d2-943c-45b3-9c95-b2329c16f958');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (146, 'aa32c014-1071-4d70-bcfd-fcf27096a73e');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (147, 'c0e58ac0-5ec2-466e-b80e-13b1546182d3');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (148, 'aaf08ccf-45f3-475d-bee2-2c70c1482e51');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (149, 'd4b1cca2-17dc-4b79-bc8f-8af2b82872c9');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (150, '5017938a-4506-493a-a5b1-70b71b5ebce4');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (151, '9ac7f83a-4066-4d55-bfed-bbb75fb90681');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (152, 'ce49bb33-de4f-43dd-8bd8-9fdec68e6375');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (153, 'c1ecc088-f74b-45d7-98e0-d05cd0f65ab2');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (154, '73c3c61b-2089-488e-8e49-550ee6a35367');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (155, 'ffa224f3-13b9-421c-9793-25706a8c1109');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (156, '7bbc1228-972f-406c-9221-998c0daa99f6');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (157, '1b724e76-1ef8-4efb-a766-f97551229a16');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (158, 'b7a27bd6-5ab5-409f-a3a9-c6538fcf2430');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (159, '8edd17c6-57b5-4fa5-9770-f5d6af723fd3');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (160, 'bf05872a-a10b-4ae0-9a41-35d2a977df4b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (161, 'c5a54aef-e93b-461f-9104-f271b7187013');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (162, 'bdf09696-65ca-4570-a8a0-7f1717443755');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (163, '52acd04a-877a-4239-a1ad-4c1d2931b24c');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (164, '950d9858-0578-423b-86d2-ba54b3958a4e');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (165, '79685a86-b8c2-4a41-b7cd-c9925e27b35f');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (166, 'bcfa3695-5cff-4beb-89d0-33e8a8ec054b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (167, 'ea041e50-5d0b-4884-9e93-1f208a3f3f59');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (168, 'e1ff6d21-e60f-4dc0-86eb-89ef4ce67887');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (169, '5b42cb1c-f9d4-417f-a3dd-9eb0d807d93b');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (170, 'b8362b38-d55f-47b3-b28a-090734a78409');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (171, '589d357f-3a75-4f19-8920-e6d8242ab183');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (172, 'fcdee9e2-b1f6-4486-8970-dc55f5577c3e');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (173, '7535b00f-7e6c-4e17-a9eb-7b0ccd706887');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (174, 'cf77e231-904a-488f-8385-ffd077503c81');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (175, 'f6ff6526-bf2c-4bab-a395-650a33624d28');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (176, '4201aee5-c4c4-48b0-bdf6-617034be67d0');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (177, '4f076bf3-02a6-47bf-b037-be22bfcdd664');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (178, '7ac682bc-d16d-4aaf-a131-cac8c0a07e3c');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (179, 'c71acc5e-7db9-4ff9-a441-eb1db1de2fb8');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (180, '5c4d5665-db7a-42e2-967c-b24a3b0cb96d');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (181, '9543d27d-9a76-491e-91a9-040ac023eef4');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (182, '7d662485-bf89-4b75-8929-906913a53923');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (183, '243782f8-1552-44c5-a6f1-ac6414bd8c06');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (184, 'ad435aa0-de3f-4d1f-86dc-9fb68558f087');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (185, '382852fa-133b-42d1-89b3-0cb34195b854');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (186, '842f68ad-f18c-4109-8d59-8e8908536b43');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (187, '57ef2190-a991-4ed2-937e-baa98d9bf6c1');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (188, 'e344247a-48db-4912-8d9f-c58e3d97967f');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (189, '522c4d4d-6107-4ed3-9906-1fdf3cdc87d1');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (190, 'aa2859bb-a5e5-4f14-b96c-6c430a7a7999');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (191, '488fee07-77da-45c6-bd8c-b3b4c4eade3e');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (192, '07c4266b-957b-436e-99aa-78c26a9d8d90');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (193, 'dbb9bf64-5f4d-4d7d-baf2-e19eac317788');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (194, '77ba3f99-4ca7-4be5-9d14-92da6ce4e3a7');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (195, '8302bdb5-b779-4a32-b010-5acfd7e3d80a');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (196, '80e7c970-48a5-4463-92fa-49900767e1dd');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (197, '2bc34269-5693-4607-bff7-5a38220c362e');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (198, '5a3cc6a1-5581-4b82-a9d2-0f1e71355e01');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (199, 'b3d7697d-4bbc-418f-9fd4-58d69abf1ad9');
INSERT INTO `Transaction_Details` (`Record_id`, `TransactionID`) VALUES (200, '548e8df7-7d4e-4908-99ee-73140bba9cce');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
