-- MySQL Script generated by MySQL Workbench
-- Wed Dec  2 15:23:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WeFlyU
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WeFlyU` ;

-- -----------------------------------------------------
-- Schema WeFlyU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WeFlyU` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
SHOW WARNINGS;
USE `WeFlyU` ;

-- -----------------------------------------------------
-- Table `Aircraft`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Aircraft` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Aircraft` (
  `aircraftSign` VARCHAR(100) NOT NULL,
  `aircraftType` VARCHAR(45) NOT NULL,
  `aircraftCapacity` INT(11) NOT NULL,
  PRIMARY KEY (`aircraftSign`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Charter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Charter` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Charter` (
  `charter#` INT NOT NULL,
  `charterDate` DATE NOT NULL,
  `charterDest` VARCHAR(100) NOT NULL,
  `charterMiles` INT(11) NOT NULL,
  `charterFee` VARCHAR(45) NOT NULL,
  `Customer_custID` INT NOT NULL,
  `Customer_custID1` INT NOT NULL,
  `Aircraft_aircraftSign` VARCHAR(100) NOT NULL,
  `Aircraft_aircraftSign1` VARCHAR(100) NOT NULL,
  `Pilot_pilotSSN` INT(20) NOT NULL,
  `Pilot_pilotSSN1` INT(20) NOT NULL,
  PRIMARY KEY (`charter#`, `Customer_custID`, `Customer_custID1`, `Aircraft_aircraftSign`, `Aircraft_aircraftSign1`, `Pilot_pilotSSN`, `Pilot_pilotSSN1`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Customer` (
  `custID` INT NOT NULL,
  `custName` VARCHAR(100) NOT NULL,
  `custAddr` VARCHAR(200) NOT NULL,
  `custContact` VARCHAR(45) NOT NULL,
  `custPhone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`custID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `custID_UNIQUE` ON `Customer` (`custID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pilot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pilot` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pilot` (
  `pilotSSN` INT(20) NOT NULL,
  `pilotName` VARCHAR(100) NOT NULL,
  `pilotLicRenew` DATE NOT NULL,
  `pilotHireDate` DATE NOT NULL,
  PRIMARY KEY (`pilotSSN`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `pilotSSN_UNIQUE` ON `Pilot` (`pilotSSN` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Aircraft`
-- -----------------------------------------------------
START TRANSACTION;
USE `WeFlyU`;
INSERT INTO `Aircraft` (`aircraftSign`, `aircraftType`, `aircraftCapacity`) VALUES ('DCM6304', 'BE350', 6);
INSERT INTO `Aircraft` (`aircraftSign`, `aircraftType`, `aircraftCapacity`) VALUES ('JMD100', 'Citation 650', 8);
INSERT INTO `Aircraft` (`aircraftSign`, `aircraftType`, `aircraftCapacity`) VALUES ('JXR120', 'Citation 550', 8);
INSERT INTO `Aircraft` (`aircraftSign`, `aircraftType`, `aircraftCapacity`) VALUES ('KFS300', 'BE90', 4);
INSERT INTO `Aircraft` (`aircraftSign`, `aircraftType`, `aircraftCapacity`) VALUES ('XYZ220', 'Falcoln 900', 20);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Charter`
-- -----------------------------------------------------
START TRANSACTION;
USE `WeFlyU`;
INSERT INTO `Charter` (`charter#`, `charterDate`, `charterDest`, `charterMiles`, `charterFee`, `Customer_custID`, `Customer_custID1`, `Aircraft_aircraftSign`, `Aircraft_aircraftSign1`, `Pilot_pilotSSN`, `Pilot_pilotSSN1`) VALUES (1001, '2020-05-03', 'Nashville, TN', 728, '$13,461.00', 1, 1, 'KFS300', 'KFS300', 216231013, 216231013);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `WeFlyU`;
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (1, 'Nationwide Insurance', '100 Nationwide Blvd, Columbus, OH  43001', 'Katelyn Shanahan', '6146003311');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (2, 'Checkers Distributor', '123 Dussel Dr., Maumee, OH  43557', 'Carol Hall', '4193601220');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (3, 'City of Columbus', '10 State St., Columbus, OH  43061', 'Mitchell Handras', '4402552573');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (4, 'Sunwest Corp.', '439 S. Hampton Ave, Maumee, OH  43537', 'David McElroy', '4192442311');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (5, 'City of Columbus', '10 State St., Columbus, OH  43061', 'Mitchell Handras', '4402552573');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (6, 'Nationwide Insurance', '100 Nationwide Blvd, Columbus, OH  43001', 'Katelyn Shanahan', '6146003311');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (7, 'Martin Associates', '105 Erie St., Toledo, OH  43601', 'James Martin', '4192410000');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (8, 'Checkers Distributor', '123 Dussel Dr., Maumee, OH  43557', 'Carol Hall', '4193601220');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (9, 'Martin Associates', '105 Erie St., Toledo, OH  43601', 'James Martin', '4192410000');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (10, 'Martin Associates', '105 Erie St., Toledo, OH  43601', 'James Martin', '4192410000');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (11, 'Destination Ohio', '4323 Bertrol Ave, Columbus, OH 43014', 'Lesline Simpson', '6144731850');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (12, 'Destination Ohio', '4323 Bertrol Ave, Columbus, OH 43014', 'Lesline Simpson', '6144731850');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (13, 'City of Columbus', '10 State St., Columbus, OH  43061', 'Mitchell Handras', '4402552573');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (14, 'Nationwide Insurance', '100 Nationwide Blvd, Columbus, OH  43001', 'Katelyn Shanahan', '6146003311');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (15, 'Martin Associates', '105 Erie St., Toledo, OH  43601', 'James Martin', '4192410000');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (16, 'Checkers Distributor', '123 Dussel Dr., Maumee, OH  43557', 'Carol Hall', '4193601220');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (17, 'Martin Associates', '105 Erie St., Toledo, OH  43601', 'James Martin', '4192410000');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (18, 'Martin Associates', '105 Erie St., Toledo, OH  43601', 'James Martin', '4192410000');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (19, 'Destination Ohio', '4323 Bertrol Ave, Columbus, OH 43014', 'Lesline Simpson', '6144731850');
INSERT INTO `Customer` (`custID`, `custName`, `custAddr`, `custContact`, `custPhone`) VALUES (20, 'Destination Ohio', '4323 Bertrol Ave, Columbus, OH 43014', 'Lesline Simpson', '6144731850');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Pilot`
-- -----------------------------------------------------
START TRANSACTION;
USE `WeFlyU`;
INSERT INTO `Pilot` (`pilotSSN`, `pilotName`, `pilotLicRenew`, `pilotHireDate`) VALUES (216841008, 'Hayden Ross', '2022-08-24', '2020-10-24');
INSERT INTO `Pilot` (`pilotSSN`, `pilotName`, `pilotLicRenew`, `pilotHireDate`) VALUES (216950321, 'Maggie Oliver', '2022-09-11', '1988-08-25');

COMMIT;

